### ISSUE TITLE
incompatible with sprintdoc template

### ISSUE THREAD

**Issue by schplurtz** [saggi-dw/dwtimeline#3]
Hi,

This is a nice plugin. but there is a compatibility problem with the [sprintdoc](https://www.dokuwiki.org/template:sprintdoc) template. As soon as dwtimeline is installed, the content of the left sidebar of the sprintdoc template disappears.

The problem is with your styles. If I remove the file `lib/plugins/dwtimeline/style.css`, and purge the caches, the sidebar reappears.

I gave a quick look at this file, and I can see that you use very "common" class names such as `content`, `container`, `left`, `right`.  These are used by the template and could be the source of this issue. You probably have to make your selectors more specific some way or another. Also, the first rule `* { box-sizing: border-box; }` seems a bit invasive.

**Comment by saggi-dw** [comment]
Thank you for the feedback and the bug report. I'm fairly new to PHP and also CSS and still learning.
I have renamed some classes and also removed the greedy Asterix.

**Comment by saggi-dw** [comment]
I hope that is fixed now. I have tested three templates: dokuwiki, bootstrap3, sprintdoc.
Maybe you could have a look too?
Thank you very much!

**Comment by schplurtz** [comment]
Thank you for your quick answer and for trying with different templates. Now it's stopped suppressing the sidebar.

However, with sprintdoc, `.tlcontent` has white background, just the same as the rest of the page, so this is a bit deceiving. With this template, `@ini_background_neu`is `#FFF` by default as is `@ini_background`. I guess this is not easy to find an `@something` that would work for all templates. I've added a note on the [wiki page](https://www.dokuwiki.org/plugin:dwtimeline#configuration_and_settings) that indicate how one can change the colors.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/1008292/178932701-2e5d7b9e-38de-462c-814e-476df67b15b8.png">

That's a minor problem though, and for me the initial problem is solved.

Thanks again

**Comment by saggi-dw** [comment]
Thank you for the feedback and the documentation update!
